name: shell commands

on: push

jobs:
 run-shell-ommends:
  runs-on: ubunto-latest
  steps:
   - name: echo a string
     run: echo "Hello String"
   - name: multiline script
     run: |
      node -v
      npm -v 
